### ISSUE TITLE
[bug] After installing Port on a M1 Mac Pro the following JS error message appears

### ISSUE THREAD

**Issue by jpzk** [jalehman/port#234]
**Bug Description*
After installing Port on a M1 Mac Pro the following JS error message appears

**To Reproduce**
1. Start port

Uncaught Exception:
Error: node-loader:
Error: dlopen(/Applications/port.app/Contents/Resources/app/.webpack/main/9d3d63e16e6ba20f5c94ce4397a299ad.node, 0x0001): tried: '/Applications/port.app/Contents/Resources/app/.webpack/main/9d3d63e16e6ba20f5c94ce4397a299ad.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/port.app/Contents/Resources/app/.webpack/main/9d3d63e16e6ba20f5c94ce4397a299ad.node' (no such file), '/Applications/port.app/Contents/Resources/app/.webpack/main/9d3d63e16e6ba20f5c94ce4397a299ad.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
at Object.879 (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:101711)
at i (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:297730)
at Object.2807 (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:106562)
at i (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:297730)
at Object.8892 (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:102489)
at i (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:297730)
at Object.769 (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:143520)
at i (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:297730)
at Object.9979 (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:129110)
at i (/Applications/port.app/Contents/Resources/app/.webpack/main/index.js:2:297730)

**Expected Behavior**

**Screenshots**

**Environment:**
 - OS: Apple M1 Pro Ventura 13.1 (22C65)

 - Version: Port-arm64.dmg v1.10.0 - Support for Urbit 1.13 binary
 - Port Version: v1.10.0 - Support for Urbit 1.13 binary

**Comment by a-moreira** [comment]
I'm getting the same error

![Screenshot 2023-02-27 at 16 37 29](https://user-images.githubusercontent.com/48456867/221665378-a90d75d6-f6d3-4661-b881-03e0578bc312.png)
